name: Release

on:
  push:
    tags:
      - "release"
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  release:
    if: (github.event_name == 'push' && github.ref == 'refs/tags/release') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Python Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 10.5.3
          extra_plugins: |
            python-semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}